# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mindu',
                'doc_host': 'https://riversdark.github.io',
                'git_url': 'https://github.com/riversdark/mindu',
                'lib_path': 'mindu'},
  'syms': {'mindu.core': {'mindu.core.foo': ('core.html#foo', 'mindu/core.py')}}}
