# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['download_pdb']

# %% ../nbs/00_utils.ipynb 4
def download_pdb(pdb_code):
    import os.path
    if not os.path.isfile(pdb_code + ".pdb"):
        import urllib.request
        url = "https://files.rcsb.org/download/" + pdb_code + ".pdb"
        urllib.request.urlretrieve(url, pdb_code + ".pdb")
        print("Downloaded " + pdb_code + ".pdb")
    else:
        print(pdb_code + ".pdb already exists")

